name: Deploy to EC2

on:
  push:
    branches:
      - dev

  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:

  # ----------------------
  # PROD DEPLOY
  # ----------------------
  deploy-prod:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "======== PROD Deployment ========"
            cd /opt/waggle/WaggleAPIServer
            git fetch origin
            git checkout main
            git pull origin main
            ./gradlew clean build -x test
            cp build/libs/WaggleAPIServer-0.0.1-SNAPSHOT.jar /opt/waggle/app.jar
            sudo systemctl restart waggle
            sudo systemctl status waggle --no-pager
            echo "======== PROD DONE ========"


  # ----------------------
  # DEV DEPLOY
  # ----------------------
  deploy-dev:
    if: github.ref == 'refs/heads/dev'   # dev로 push될 때만 실행
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Development
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "======== DEV Deployment ========"
            cd /opt/waggle/WaggleAPIServer
            git fetch origin
            git checkout dev
            git pull origin dev
            ./gradlew clean build -x test
            cp build/libs/WaggleAPIServer-0.0.1-SNAPSHOT.jar /opt/waggle-dev/app.jar
            sudo systemctl restart waggle-dev
            sudo systemctl status waggle-dev --no-pager
            echo "======== DEV DONE ========"
